services:
  dbsql:
    image: mysql:8.0
    container_name: mysql
    networks:
      - medilabo-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: patients
      MYSQL_USER: user
      MYSQL_PASSWORD: rootroot
    ports:
      - "3307:3306"
    volumes:
      - patients_db:/var/lib/mysql


  dbmongodb:
    image: mongo
    container_name: mongodb
    networks:
      - medilabo-network
    environment:
      MONGO_INITDB_DATABASE: note
    ports:
      - "27018:27017"
    volumes:
      - notes_db:/data/db

  patients:
    build: ./patient
    container_name: patients
    networks:
      - medilabo-network
    ports:
      - "8092:8092"
    depends_on:
      - dbsql
    environment:
      DB_USER: root
      DB_PWD: root

  notes:
    build: ./note
    container_name: notes
    networks:
      - medilabo-network
    ports:
      - "8093:8093"
    depends_on:
      - dbmongodb


  diabete:
    build: ./risk
    container_name: risk
    networks:
      - medilabo-network
    ports:
      - "8094:8094"

  gateway:
    build: ./gateway
    container_name: gateway
    networks:
      - medilabo-network
    ports:
      - "8090:8090"

  medilab_front:
    build: ./front
    container_name: medilab-front
    networks:
      - medilabo-network
    ports:
      - "8091:8091"

volumes:
  patients_db:
    
  notes_db:

networks:
  medilabo-network:

